
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Jun 04 15:41:06 CST 2025
//----------------------------------------------------

package analizadores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int LLAVE_IZQ = 11;
  public static final int LLAVE_DER = 12;
  public static final int FRENTE_LIBRE = 8;
  public static final int PUNTO_COMA = 10;
  public static final int FRENTE_OBSTACULO = 9;
  public static final int ERROR = 14;
  public static final int GIRAR = 3;
  public static final int EOF = 0;
  public static final int IZQUIERDA = 7;
  public static final int NUMERO = 13;
  public static final int error = 1;
  public static final int DERECHA = 6;
  public static final int MOVER = 2;
  public static final int REPETIR = 4;
  public static final int SI = 5;
  public  static int IDENTIFICADOR;
}

